### ISSUE TITLE
The SecretBox algorithm in pinenacl-dart is different from TweetNaCl and libsodium

### ISSUE THREAD

**Issue by redsolver** [ilap/pinenacl-dart#15] opened 2021-07-18 15:48 UTC
When encrypting a payload with a size of more than 16 KB using the same key and nonce, TweetNaCl (https://www.npmjs.com/package/tweetnacl) and libsodium (https://pub.dev/packages/sodium) generate exactly the same ciphertext (as expected).

But when trying the same with this library:
- the first 16 bytes are completely different
- the ciphertext until about 16 KB is correct (same output as TweetNaCl and libsodium)
- everything after 16 KB is different from TweetNaCl and libsodium

It would be great if the output of pinenacl-dart would be compatible the same algorithm in other crypto libraries, thanks!

**Comment by ilap** [comment] 2021-07-18 21:50
Hi, 

Can you pls provide some test vector to check?

Cheers,

Pal

**Comment by redsolver** [comment] 2021-07-18 22:08
Here you go: https://github.com/redsolver/pinenacl-bug-demo
There is the input file, the output files, the code and the diff command I used.

**Comment by ilap** [comment] 2021-07-19 01:43
Thank you very much, it will be fixed soon. 
I have found the root cause of the issue. It is some sign issues.

**Closed** 2021-07-19 22:38 UTC

**Comment by ilap** [comment] 2021-07-19 22:41
Please use the latest package the v0.3.2.

Cheers,

Pal
